version: '3'
services:
  redis:
    image: redis:latest
    container_name: redis-container
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: always
    mem_limit: 256M # 메모리 제한
    cpus: "0.3"    # CPU 30% 제한

volumes:
  redis-data:
    driver: local