# Generated by Django 5.1.3 on 2024-12-14 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("DBapp", "0003_component_partofspeech_topic_word_wordcomponent_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="word",
            name="word",
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
    ]
