version: '3.8'

services:
  web:
    build:
      context: .
    ports:
      - "80:80"
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - DJANGO_SETTINGS_MODULE=myproject.settings
